# Generated by Django 5.2.8 on 2025-11-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="description",
        ),
        migrations.AddField(
            model_name="plan",
            name="price_hourly",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="plan",
            name="storage_gb",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="template",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="bandwidth_gb",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plan",
            name="cpu_cores",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price_monthly",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="plan",
            name="ram_mb",
            field=models.IntegerField(default=0),
        ),
    ]
