# Generated by Django 5.0.6 on 2025-11-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_template_description_plan_price_hourly_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
