# Generated by Django 5.0.6 on 2025-11-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_plan_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="envvar",
            name="is_secret",
            field=models.BooleanField(default=False),
        ),
    ]
