# Generated by Django 5.2.8 on 2025-11-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_github_avatar_url_user_github_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_access_token",
            field=models.TextField(blank=True, help_text="GitHub OAuth access token"),
        ),
        migrations.AddField(
            model_name="user",
            name="github_refresh_token",
            field=models.TextField(blank=True, help_text="GitHub OAuth refresh token"),
        ),
        migrations.AddField(
            model_name="user",
            name="github_token_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Token expiration time", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="github_token_scope",
            field=models.CharField(
                blank=True, help_text="OAuth scopes granted", max_length=255
            ),
        ),
    ]
