# Generated by Django 5.0.6 on 2025-11-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=100)),
                ("repo_name", models.CharField(max_length=100)),
                ("branch", models.CharField(default="main", max_length=100)),
                ("github_id", models.IntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("organization", "repo_name")},
            },
        ),
    ]
