# Generated by Django 5.0.6 on 2025-11-23 14:40

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="ami_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="credential_type",
            field=models.CharField(
                default="demo", help_text="Type of credential used", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="instance_type",
            field=models.CharField(default="t3.micro", max_length=50),
        ),
        migrations.AddField(
            model_name="instance",
            name="private_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="region",
            field=models.CharField(default="us-east-1", max_length=50),
        ),
        migrations.AlterField(
            model_name="instance",
            name="cpu",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="instance_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="ram_mb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("stopping", "Stopping"),
                    ("stopped", "Stopped"),
                    ("terminated", "Terminated"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AWSCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this credential set",
                        max_length=100,
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("demo", "Demo Credentials"),
                            ("user", "User Credentials"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("aws_access_key", encrypted_model_fields.fields.EncryptedCharField()),
                ("aws_secret_key", encrypted_model_fields.fields.EncryptedCharField()),
                ("region", models.CharField(default="us-east-1", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aws_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="infra.awscredential",
            ),
        ),
    ]
