# Generated by Django 5.0.6 on 2025-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra", "0002_instance_ami_id_instance_credential_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="auto_terminate_at",
            field=models.DateTimeField(
                blank=True, help_text="When to auto-terminate this instance", null=True
            ),
        ),
    ]
