# Generated by Django 5.0.6 on 2025-11-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra", "0003_instance_auto_terminate_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="port",
            field=models.IntegerField(
                blank=True, help_text="Application port", null=True
            ),
        ),
    ]
