# Generated by Django 5.0.6 on 2025-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra", "0004_instance_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="security_group_id",
            field=models.CharField(
                blank=True,
                help_text="AWS Security Group ID for cleanup",
                max_length=50,
                null=True,
            ),
        ),
    ]
